//
//  Conversion.h
//  DOT
//
//  Created by Woncheol Heo on 2018. 7. 2..
//  Copyright © 2018년 wisetracker. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Product.h"
#import "CustomValue.h"

@interface Conversion : NSObject

@property (nonatomic) NSString *keywordCategory;
@property (nonatomic) NSString *keyword;
@property (nonatomic) CustomValue *customValue;
@property (nonatomic) Product *product;
@property (nonatomic) BOOL pushAgreement;
@property (nonatomic) double g1;
@property (nonatomic) double g2;
@property (nonatomic) double g3;
@property (nonatomic) double g4;
@property (nonatomic) double g5;
@property (nonatomic) double g6;
@property (nonatomic) double g7;
@property (nonatomic) double g8;
@property (nonatomic) double g9;
@property (nonatomic) double g10;
@property (nonatomic) double g11;
@property (nonatomic) double g12;
@property (nonatomic) double g13;
@property (nonatomic) double g14;
@property (nonatomic) double g15;
@property (nonatomic) double g16;
@property (nonatomic) double g17;
@property (nonatomic) double g18;
@property (nonatomic) double g19;
@property (nonatomic) double g20;
@property (nonatomic) double g21;
@property (nonatomic) double g22;
@property (nonatomic) double g23;
@property (nonatomic) double g24;
@property (nonatomic) double g25;
@property (nonatomic) double g26;
@property (nonatomic) double g27;
@property (nonatomic) double g28;
@property (nonatomic) double g29;
@property (nonatomic) double g30;
@property (nonatomic) double g31;
@property (nonatomic) double g32;
@property (nonatomic) double g33;
@property (nonatomic) double g34;
@property (nonatomic) double g35;
@property (nonatomic) double g36;
@property (nonatomic) double g37;
@property (nonatomic) double g38;
@property (nonatomic) double g39;
@property (nonatomic) double g40;
@property (nonatomic) double g41;
@property (nonatomic) double g42;
@property (nonatomic) double g43;
@property (nonatomic) double g44;
@property (nonatomic) double g45;
@property (nonatomic) double g46;
@property (nonatomic) double g47;
@property (nonatomic) double g48;
@property (nonatomic) double g49;
@property (nonatomic) double g50;
@property (nonatomic) double g51;
@property (nonatomic) double g52;
@property (nonatomic) double g53;
@property (nonatomic) double g54;
@property (nonatomic) double g55;
@property (nonatomic) double g56;
@property (nonatomic) double g57;
@property (nonatomic) double g58;
@property (nonatomic) double g59;
@property (nonatomic) double g60;
@property (nonatomic) double g61;
@property (nonatomic) double g62;
@property (nonatomic) double g63;
@property (nonatomic) double g64;
@property (nonatomic) double g65;
@property (nonatomic) double g66;
@property (nonatomic) double g67;
@property (nonatomic) double g68;
@property (nonatomic) double g69;
@property (nonatomic) double g70;
@property (nonatomic) double g71;
@property (nonatomic) double g72;
@property (nonatomic) double g73;
@property (nonatomic) double g74;
@property (nonatomic) double g75;
@property (nonatomic) double g76;
@property (nonatomic) double g77;
@property (nonatomic) double g78;
@property (nonatomic) double g79;
@property (nonatomic) double g80;

- (void)setCustomValues:(CustomValue *)customValue;
- (void)setMicroConversion:(NSString *)constant value:(double)value;
- (void)setMicroConversionG1:(double)value;
- (void)setMicroConversionG2:(double)value;
- (void)setMicroConversionG3:(double)value;
- (void)setMicroConversionG4:(double)value;
- (void)setMicroConversionG5:(double)value;
- (void)setMicroConversionG6:(double)value;
- (void)setMicroConversionG7:(double)value;
- (void)setMicroConversionG8:(double)value;
- (void)setMicroConversionG9:(double)value;
- (void)setMicroConversionG10:(double)value;
- (void)setMicroConversionG11:(double)value;
- (void)setMicroConversionG12:(double)value;
- (void)setMicroConversionG13:(double)value;
- (void)setMicroConversionG14:(double)value;
- (void)setMicroConversionG15:(double)value;
- (void)setMicroConversionG16:(double)value;
- (void)setMicroConversionG17:(double)value;
- (void)setMicroConversionG18:(double)value;
- (void)setMicroConversionG19:(double)value;
- (void)setMicroConversionG20:(double)value;
- (void)setMicroConversionG21:(double)value;
- (void)setMicroConversionG22:(double)value;
- (void)setMicroConversionG23:(double)value;
- (void)setMicroConversionG24:(double)value;
- (void)setMicroConversionG25:(double)value;
- (void)setMicroConversionG26:(double)value;
- (void)setMicroConversionG27:(double)value;
- (void)setMicroConversionG28:(double)value;
- (void)setMicroConversionG29:(double)value;
- (void)setMicroConversionG30:(double)value;
- (void)setMicroConversionG31:(double)value;
- (void)setMicroConversionG32:(double)value;
- (void)setMicroConversionG33:(double)value;
- (void)setMicroConversionG34:(double)value;
- (void)setMicroConversionG35:(double)value;
- (void)setMicroConversionG36:(double)value;
- (void)setMicroConversionG37:(double)value;
- (void)setMicroConversionG38:(double)value;
- (void)setMicroConversionG39:(double)value;
- (void)setMicroConversionG40:(double)value;
- (void)setMicroConversionG41:(double)value;
- (void)setMicroConversionG42:(double)value;
- (void)setMicroConversionG43:(double)value;
- (void)setMicroConversionG44:(double)value;
- (void)setMicroConversionG45:(double)value;
- (void)setMicroConversionG46:(double)value;
- (void)setMicroConversionG47:(double)value;
- (void)setMicroConversionG48:(double)value;
- (void)setMicroConversionG49:(double)value;
- (void)setMicroConversionG50:(double)value;
- (void)setMicroConversionG51:(double)value;
- (void)setMicroConversionG52:(double)value;
- (void)setMicroConversionG53:(double)value;
- (void)setMicroConversionG54:(double)value;
- (void)setMicroConversionG55:(double)value;
- (void)setMicroConversionG56:(double)value;
- (void)setMicroConversionG57:(double)value;
- (void)setMicroConversionG58:(double)value;
- (void)setMicroConversionG59:(double)value;
- (void)setMicroConversionG60:(double)value;
- (void)setMicroConversionG61:(double)value;
- (void)setMicroConversionG62:(double)value;
- (void)setMicroConversionG63:(double)value;
- (void)setMicroConversionG64:(double)value;
- (void)setMicroConversionG65:(double)value;
- (void)setMicroConversionG66:(double)value;
- (void)setMicroConversionG67:(double)value;
- (void)setMicroConversionG68:(double)value;
- (void)setMicroConversionG69:(double)value;
- (void)setMicroConversionG70:(double)value;
- (void)setMicroConversionG71:(double)value;
- (void)setMicroConversionG72:(double)value;
- (void)setMicroConversionG73:(double)value;
- (void)setMicroConversionG74:(double)value;
- (void)setMicroConversionG75:(double)value;
- (void)setMicroConversionG76:(double)value;
- (void)setMicroConversionG77:(double)value;
- (void)setMicroConversionG78:(double)value;
- (void)setMicroConversionG79:(double)value;
- (void)setMicroConversionG80:(double)value;
@end
